version: "3.8"
services:
    # mysql Database container
    ds-mysql:
        image: mysql:8.0.34
        container_name: ds-mysql
        ports:
            - ${MYSQL_PORT}:3306
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ds-mysql:/var/lib/mysql
    # phpmyadmin container
    ds-adminer:
        image: adminer
        container_name: ds-adminer
        ports:
            - "${ADMINER_PORT}:8080"
    # Symfony apache project container
    ds-app:
        build: ./php
        container_name: ds-app
        restart: unless-stopped
        env_file:
            - ../../.env.local
        working_dir: /var/www/
        volumes:
            - ../../:/var/www
    ds-web:
        image: nginx:latest
        container_name: ds-web
        restart: unless-stopped
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ../../:/var/www
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        environment:
            - TZ=${TIME_ZONE}
    ds-es:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
        container_name: ds-es
        user: "1000:1000"
        volumes:
            - ds-es:/usr/share/elasticsearch/data
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
            - cluster.routing.allocation.disk.threshold_enabled=false
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"

volumes:
    ds-mysql:
        driver: local
    ds-es:
        driver: local
